apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vm-console-proxy-ulam
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy-1/vm-console-proxy-ulam@sha256:482d11d0fc5be6e3acd223c57b463247e10c6774b20387ceb2bff958f732e512
        name: container-image
        resources: {}
status: {}
