apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vm-console-proxy-ulam
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/aaguirre-tenant/vm-console-proxy-1/vm-console-proxy-ulam@sha256:728e4286c59ab3abdef062f9099d6d98d6df9317fabdc1a290938b80d22f2fa1
        name: container-image
        resources: {}
status: {}
